prop:
#每个项目/模式都要变的
  sys:
    #/**项目名*/
    sysname: sts
    #/**根目录名，通常是项目名，偶尔有意外 ex./bbb or "" 根目录用空格不要用/ */
    base: /sts    
    #/**域名 ex.http://aaa.com */
    website: http://sts.kongjianhao.cn
    #/**开发模式，0/-1表示非开发，大于0表示为开发者userId*/
    devmode: 0
    #/**是否运行定时任务，多应用中，只有一台运行定时任务*/
    boolTask: true
    #/**网站域名 ex.http://www.xxx.com */
    domain: http://sts.kongjianhao.cn
    #/**网站英文名  */
    webnamee: sts
    #/**网站中文名  */
    webnamec: 空间号  
#通用配置，不太会变的
  my:  
    name: zmaxdEFAULT
    title: GoodMan
    value: ${random.value}
    number: ${random.int}
    bignumber: ${random.long}
    test1: ${random.int(10)}
    test2: ${random.int[10,20]}
    #/**一些静态图的图床 ex.http://aaa.com */
    imgbase: ${prop.sys.website}       
    #/**静态资源站点  ex.http://aaa.com or "" 根目录用空格不要用/ */
    resbase: ${prop.sys.base}/res  
    #/**登录地址 */
    loginurl: ${prop.sys.base}/login.html
    #/**user路径下不需要登录的地址 */
    loginignor: 
      - /test1
      - /test2
      - /dbinit.html    
    #/**默认的管理员密码*/
    adminpwd: admin123
    #file:///d:/opt/sts 
    hddir: file:///F:/git-study/nowhere/src/main/webapp
#应用配置
  me:
  #/**辅助节点名称 空着或main表示主服务*/
     vicenodename: web024dev
  #/**mqtt的服务器地址和端口 ex.tcp://192.168.0.97:1883 tcp://118.178.138.87:1883 */
     mqtturl: tcp://118.178.138.87:1883
  #/**mqtt的服务器订阅者账号 */
     mqttsubusername: guest
  #/**mqtt的服务器订阅者密码 */
     mqttsubpwd: guest
  #/**mqtt的服务器发布者账号 */
     mqttpubusername: guest
  #/**mqtt的服务器发布者密码 */
     mqttpubpwd: guest
  #/**阿里大于短信签名*/
     aliSmsFreeSignName: aaa    
  #/**这个机器上微信token获取方式：wx:直接向微信后台申请,db:向数据库申请,test:假token,none:不申请*/
     wxTokenMode: none
  #/**个推AppID*/
     gtAppID: LWZl6u9DMq5UQTjpVVHqo7
  #/**个推AppSecret*/
     gtAppSecret: 3tt4q36Q2X9TIKbSVwLeE6
  #/**个推AppKey*/
     gtAppKey: hSsKPzaNkx8NVuz2rsJkF5
  #/**个推MasterSecret*/
     gtMasterSecret: Ae1yNI00AZACelrr2OT0V6
  #/**支付宝商户号*/
     alipaypartner: 2088621662719550
  #/**支付宝商户私钥*/
     alipayprivatekey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBANfNn2bTQc7bikxEfNkAmp3WTMu/PnC05J8/4K3FHzzA6V+tT9JAqiB4FZbYB2C0BuDiNwD+MQGeZ19mvwvik6KTpfpfgqGi1FNPP4T7QMqG69UGQg11zRogIMdCyN1xhdVk4e93U7ysMv3MIEsy0Zds7rR84ecD3FwGtV/tsMyhAgMBAAECgYEAtqGPAC9TJyQGw4rGecOYFnGxJlEgH7QHM3qUw5rqV7kPB+idf9s33yihZLpIbB+PHqxzTkTQ5oTPCR7kGcPTmhm9qlRgEtz56a6XsI3yvKQFCT649a/N0heD6s/d5+G9KfyaDpjSq23xtWo456LmSYdkWyW3X/JmlSBZN03tUAECQQD2lStW8vAwGEcU5UIYw40TJA5c5vpbNNEPpNcA9sLGAkH66WIK5vKNnEhV2MJ2L2o2hQLIWCg0R7vSqhbKZYchAkEA4AuF/8tTpwuStCeAeTohO6oQSGzieoshlIn6WRb3gTJ2AisgKVbb9f46VY6tKQBCx030u+NxkE+U9bUmODIVgQJAbZn8O5ecHySLY8RLTsqMyDc8kxqvqR6e1j9Euc704CJcxXQ6+fGRWlRe6pmARhvpL/aLOBXHOQWxfH/RxYC/QQJANtL7DlYN+VF+q7EC4idUXIpIA8EJRp1nMTb2WPiixi237N3qt9L2bmKwmaEZRHA45xZvbc7BSmP++oVCffvbgQJAbMCXfujNUuBCHHygzB79wOx4g5TNu8Bv9BZHifOLUuYzhpWk+ziwYfUtvwDj8Qc7jVyu/VNdI7rBeVl86FNzlQ==
  #/**支付宝的接口名称  接口名称，固定值*/
     alipayservice: mobile.securitypay.pay
  #/**支付宝的卖家支付宝账号  卖家支付宝账号（邮箱或手机号码格式）*/
     alipaysellerid: daxiang100_dev@163.com
  #/**支付宝的appid*/
     alipayappid: 2017062707580890   
server:
  port: 8080
  context-path: ${prop.sys.base}
# tomcat最大线程数，默认为200
  tomcat:
    max-threads: 800
# tomcat的URI编码
    uri-encoding: UTF-8
# 存放Tomcat的日志、Dump等文件的临时文件夹，默认为系统的tmp文件夹（如：C:\Users\Shanhy\AppData\Local\Temp）
    basedir: /tomcat_sts
# 最大POST数量无限制    
    max-post-size: 0
# 打开Tomcat的Access日志，并可以设置日志格式的方法：
#server.tomcat.access-log-enabled=true
#server.tomcat.access-log-pattern=
# accesslog目录，默认在basedir/logs
#server.tomcat.accesslog.directory=

spring:
  profiles:
    active: deveclipse
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/nowhere?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    max-active: 20
    initial-size: 1
    min-idle: 3
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    validation-query: select 1
  security:
    oauth2:
      resource:
        filter-order: 3
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        show_sql: false
        cache:
          use_second_level_cache: false
  redis:
     hostName=127.0.0.1
     port=6379
     pool.maxWait=-1
     pool.maxIdle=8
     pool.minIdle=0
     timeout=0
  resources:
    #${prop.my.hddir}/static/, file:///D:/z_java/yj/sts/trunk/src/main/webapp/static/   
    static-locations: ${prop.my.hddir}/static/
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: false
    suffix: .html
    #${prop.my.hddir}/templates/,file:///D:/z_java/yj/sts/trunk/src/main/webapp/templates/
    template-loader-path: ${prop.my.hddir}/templates/
    order: 1
    settings:
      default_encoding: UTF-8
      classic_compatible: true
      tag_syntax: auto_detect
      template_update_delay: 0
      url_escaping_charset: UTF-8
      locale: zh_CN
      boolean_format: true,false
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      number_format: 0.######
      whitespace_stripping: true
      auto_import: /ftl/pony/index.ftl as p,/ftl/spring.ftl as s,/pages/global/ztitle.html as z

debug: false
#以下是各模式:dev
---
spring:
  profiles: dev
  resources:
     static-locations: file:///D:/opt/sts/static/  
  freemarker:
    template-loader-path: file:///D:/opt/sts/templates/  
prop:
  my:
    name: zmaxdev
---
#以下是各模式:prodwin    
spring:
  profiles: prodwin
  resources:
     static-locations: file:///opt/sts/static/  
  freemarker:
    template-loader-path: file:///opt/sts/templates/  
  datasource:
    url: jdbc:mysql://PROD_MYSQL_HOST:PROD_MYSQL_PORT/PROD_MYSQL_DBNAME?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: PROD_MYSQL_USERNAME
    password: PROD_MYSQL_PWD
prop:
  my:
    name: zmax_PROD  
---
#以下是各模式:prodlinux    
spring:
  profiles: prodlinux
  resources:
     static-locations: file:///opt/sts/static/  
  freemarker:
    template-loader-path: file:///opt/sts/templates/  
  datasource:
    url: jdbc:mysql://PROD_MYSQL_HOST:PROD_MYSQL_PORT/PROD_MYSQL_DBNAME?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: PROD_MYSQL_USERNAME
    password: PROD_MYSQL_PWD
  redis:
    hostName=127.0.0.1  
    port=6379    
    pool.maxWait=-1    
    pool.maxIdle=8    
    pool.minIdle=0    
    timeout=0
prop:
  my:
    name: zmax_PROD_LINUX
    #硬盘上的运行目录，file:///d:/opt/sts
    hddir: /opt/sts
#应用配置
  me:
  #/**这个机器上微信token获取方式：wx:直接向微信后台申请,db:向数据库申请,test:假token,none:不申请*/
     wxTokenMode: wx    
            